#!/usr/bin/env node
// `npm run clean` — remove build/dev caches so stale artifacts can't mislead a
// debugging session. Safe: everything here is regenerated by the next dev/build.
import { rmSync, existsSync } from 'node:fs';

const targets = ['node_modules/.vite', '.vite', 'dist', 'dev-dist', 'coverage'];

let removed = 0;
for (const t of targets) {
  if (!existsSync(t)) continue;
  rmSync(t, { recursive: true, force: true });
  console.log(`  removed ${t}`);
  removed += 1;
}
console.log(
  removed
    ? `Done — cleared ${removed} cache path(s). Next dev/build rebuilds fresh.`
    : 'Nothing to clean — no cache paths present.'
);
