// The German alphabet and the quiz groupings built from it.

export const ALPHABET = [
  { l: 'A', w: 'Apfel', e: 'apple' },
  { l: 'B', w: 'Brot', e: 'bread' },
  { l: 'C', w: 'Computer', e: 'computer' },
  { l: 'D', w: 'Danke', e: 'thank you' },
  { l: 'E', w: 'Elefant', e: 'elephant' },
  { l: 'F', w: 'Freund', e: 'friend' },
  { l: 'G', w: 'Glück', e: 'luck' },
  { l: 'H', w: 'Haus', e: 'house' },
  { l: 'I', w: 'Insel', e: 'island' },
  { l: 'J', w: 'Jahr', e: 'year' },
  { l: 'K', w: 'Katze', e: 'cat' },
  { l: 'L', w: 'Liebe', e: 'love' },
  { l: 'M', w: 'Mond', e: 'moon' },
  { l: 'N', w: 'Nacht', e: 'night' },
  { l: 'O', w: 'Ofen', e: 'oven' },
  { l: 'P', w: 'Pferd', e: 'horse' },
  { l: 'Q', w: 'Quelle', e: 'source' },
  { l: 'R', w: 'Regen', e: 'rain' },
  { l: 'S', w: 'Sonne', e: 'sun' },
  { l: 'T', w: 'Tag', e: 'day' },
  { l: 'U', w: 'Uhr', e: 'clock' },
  { l: 'V', w: 'Vogel', e: 'bird' },
  { l: 'W', w: 'Wasser', e: 'water' },
  { l: 'X', w: 'Xylophon', e: 'xylophone' },
  { l: 'Y', w: 'Yoga', e: 'yoga' },
  { l: 'Z', w: 'Zeit', e: 'time' },
  { l: 'Ä', w: 'Äpfel', e: 'apples', special: true },
  { l: 'Ö', w: 'Öl', e: 'oil', special: true },
  { l: 'Ü', w: 'Über', e: 'over', special: true },
  { l: 'ß', w: 'Straße', e: 'street', special: true },
];

export const ALPHABET_QUIZ_GROUPS = [
  { letters: ['U', 'Ü', 'O', 'Ö'] },
  { letters: ['A', 'Ä', 'E', 'I'] },
  { letters: ['S', 'ß', 'Z', 'W'] },
  { letters: ['B', 'P', 'D', 'T'] },
  { letters: ['V', 'W', 'F', 'B'] },
  { letters: ['G', 'K', 'J', 'Y'] },
  { letters: ['R', 'L', 'N', 'M'] },
  { letters: ['H', 'X', 'Q', 'C'] },
];
