// German lexicon — Phase B. The 40 originally-curated cards, migrated to the
// rich LexiconEntry shape. Keys are the legacy surface-form ids so SRS history
// is preserved. en values keep the legacy English string as the first gloss;
// ipa values are unchanged from the original cards.
const SRC = { dict: 'authored', license: 'MIT' };

/** @type {Record<string, object>} */
export const LEXICON = {
  // ── greetings (phrases / interjections) ──
  Hallo: {
    id: 'Hallo',
    de: 'Hallo',
    en: ['Hello'],
    pos: 'phrase',
    article: null,
    ipa: '[ˈhalo]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['greetings'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'Guten Morgen': {
    id: 'Guten Morgen',
    de: 'Guten Morgen',
    en: ['Good morning'],
    pos: 'phrase',
    article: null,
    ipa: '[ˈɡuːtn̩ ˈmɔʁɡn̩]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['greetings'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'Guten Tag': {
    id: 'Guten Tag',
    de: 'Guten Tag',
    en: ['Good day'],
    pos: 'phrase',
    article: null,
    ipa: '[ˈɡuːtn̩ taːk]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['greetings'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'Guten Abend': {
    id: 'Guten Abend',
    de: 'Guten Abend',
    en: ['Good evening'],
    pos: 'phrase',
    article: null,
    ipa: '[ˈɡuːtn̩ ˈaːbn̩t]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['greetings'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'Auf Wiedersehen': {
    id: 'Auf Wiedersehen',
    de: 'Auf Wiedersehen',
    en: ['Goodbye'],
    pos: 'phrase',
    article: null,
    ipa: '[aʊ̯f ˈviːdɐzeːən]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['greetings'],
    examples: [],
    verb: null,
    source: SRC,
  },
  Tschüss: {
    id: 'Tschüss',
    de: 'Tschüss',
    en: ['Bye'],
    pos: 'phrase',
    article: null,
    ipa: '[tʃʏs]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['greetings'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'Wie geht es dir?': {
    id: 'Wie geht es dir?',
    de: 'Wie geht es dir?',
    en: ['How are you?'],
    pos: 'phrase',
    article: null,
    ipa: '[viː ɡeːt ɛs diːɐ̯]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['greetings'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'Mir geht es gut': {
    id: 'Mir geht es gut',
    de: 'Mir geht es gut',
    en: ["I'm well"],
    pos: 'phrase',
    article: null,
    ipa: '[miːɐ̯ ɡeːt ɛs ɡuːt]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['greetings'],
    examples: [],
    verb: null,
    source: SRC,
  },
  Bitte: {
    id: 'Bitte',
    de: 'Bitte',
    en: ['Please'],
    pos: 'phrase',
    article: null,
    ipa: '[ˈbɪtə]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['greetings'],
    examples: [],
    verb: null,
    source: SRC,
  },
  Danke: {
    id: 'Danke',
    de: 'Danke',
    en: ['Thank you'],
    pos: 'phrase',
    article: null,
    ipa: '[ˈdaŋkə]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['greetings'],
    examples: [],
    verb: null,
    source: SRC,
  },

  // ── food (nouns) ──
  'das Brot': {
    id: 'das Brot',
    de: 'Brot',
    en: ['bread'],
    pos: 'noun',
    article: 'das',
    ipa: '[das bʁoːt]',
    plural: 'Brote',
    cefr: 'A1',
    freqRank: null,
    tags: ['food'],
    examples: [{ de: 'Ich esse Brot.', en: 'I eat bread.', source: 'authored' }],
    verb: null,
    source: SRC,
  },
  'der Käse': {
    id: 'der Käse',
    de: 'Käse',
    en: ['cheese'],
    pos: 'noun',
    article: 'der',
    ipa: '[deːɐ̯ ˈkɛːzə]',
    plural: 'Käse',
    cefr: 'A1',
    freqRank: null,
    tags: ['food'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'das Wasser': {
    id: 'das Wasser',
    de: 'Wasser',
    en: ['water'],
    pos: 'noun',
    article: 'das',
    ipa: '[das ˈvasɐ]',
    plural: 'Wässer',
    cefr: 'A1',
    freqRank: null,
    tags: ['food'],
    examples: [{ de: 'Ich trinke Wasser.', en: 'I drink water.', source: 'authored' }],
    verb: null,
    source: SRC,
  },
  'der Apfel': {
    id: 'der Apfel',
    de: 'Apfel',
    en: ['apple'],
    pos: 'noun',
    article: 'der',
    ipa: '[deːɐ̯ ˈapfl̩]',
    plural: 'Äpfel',
    cefr: 'A1',
    freqRank: null,
    tags: ['food'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'das Fleisch': {
    id: 'das Fleisch',
    de: 'Fleisch',
    en: ['meat'],
    pos: 'noun',
    article: 'das',
    ipa: '[das flaɪ̯ʃ]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['food'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'der Kaffee': {
    id: 'der Kaffee',
    de: 'Kaffee',
    en: ['coffee'],
    pos: 'noun',
    article: 'der',
    ipa: '[deːɐ̯ ˈkafe]',
    plural: 'Kaffees',
    cefr: 'A1',
    freqRank: null,
    tags: ['food'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'die Milch': {
    id: 'die Milch',
    de: 'Milch',
    en: ['milk'],
    pos: 'noun',
    article: 'die',
    ipa: '[diː mɪlç]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['food'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'das Bier': {
    id: 'das Bier',
    de: 'Bier',
    en: ['beer'],
    pos: 'noun',
    article: 'das',
    ipa: '[das biːɐ̯]',
    plural: 'Biere',
    cefr: 'A1',
    freqRank: null,
    tags: ['food'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'die Suppe': {
    id: 'die Suppe',
    de: 'Suppe',
    en: ['soup'],
    pos: 'noun',
    article: 'die',
    ipa: '[diː ˈzʊpə]',
    plural: 'Suppen',
    cefr: 'A1',
    freqRank: null,
    tags: ['food'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'der Zucker': {
    id: 'der Zucker',
    de: 'Zucker',
    en: ['sugar'],
    pos: 'noun',
    article: 'der',
    ipa: '[deːɐ̯ ˈtsʊkɐ]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['food'],
    examples: [],
    verb: null,
    source: SRC,
  },

  // ── travel ──
  'der Bahnhof': {
    id: 'der Bahnhof',
    de: 'Bahnhof',
    en: ['train station'],
    pos: 'noun',
    article: 'der',
    ipa: '[deːɐ̯ ˈbaːnhoːf]',
    plural: 'Bahnhöfe',
    cefr: 'A2',
    freqRank: null,
    tags: ['travel'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'der Flughafen': {
    id: 'der Flughafen',
    de: 'Flughafen',
    en: ['airport'],
    pos: 'noun',
    article: 'der',
    ipa: '[deːɐ̯ ˈfluːkhaːfn̩]',
    plural: 'Flughäfen',
    cefr: 'A2',
    freqRank: null,
    tags: ['travel'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'das Hotel': {
    id: 'das Hotel',
    de: 'Hotel',
    en: ['hotel'],
    pos: 'noun',
    article: 'das',
    ipa: '[das hoˈtɛl]',
    plural: 'Hotels',
    cefr: 'A2',
    freqRank: null,
    tags: ['travel'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'die Karte': {
    id: 'die Karte',
    de: 'Karte',
    en: ['map / ticket'],
    pos: 'noun',
    article: 'die',
    ipa: '[diː ˈkaʁtə]',
    plural: 'Karten',
    cefr: 'A2',
    freqRank: null,
    tags: ['travel'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'der Koffer': {
    id: 'der Koffer',
    de: 'Koffer',
    en: ['suitcase'],
    pos: 'noun',
    article: 'der',
    ipa: '[deːɐ̯ ˈkɔfɐ]',
    plural: 'Koffer',
    cefr: 'A2',
    freqRank: null,
    tags: ['travel'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'der Pass': {
    id: 'der Pass',
    de: 'Pass',
    en: ['passport'],
    pos: 'noun',
    article: 'der',
    ipa: '[deːɐ̯ pas]',
    plural: 'Pässe',
    cefr: 'A2',
    freqRank: null,
    tags: ['travel'],
    examples: [],
    verb: null,
    source: SRC,
  },
  links: {
    id: 'links',
    de: 'links',
    en: ['left'],
    pos: 'adv',
    article: null,
    ipa: '[lɪŋks]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['travel'],
    examples: [],
    verb: null,
    source: SRC,
  },
  rechts: {
    id: 'rechts',
    de: 'rechts',
    en: ['right'],
    pos: 'adv',
    article: null,
    ipa: '[ʁɛçts]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['travel'],
    examples: [],
    verb: null,
    source: SRC,
  },
  geradeaus: {
    id: 'geradeaus',
    de: 'geradeaus',
    en: ['straight ahead'],
    pos: 'adv',
    article: null,
    ipa: '[ɡəˈʁaːdəˌʔaʊ̯s]',
    plural: null,
    cefr: 'A2',
    freqRank: null,
    tags: ['travel'],
    examples: [],
    verb: null,
    source: SRC,
  },
  'Wo ist...?': {
    id: 'Wo ist...?',
    de: 'Wo ist...?',
    en: ['Where is...?'],
    pos: 'phrase',
    article: null,
    ipa: '[voː ɪst]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['travel'],
    examples: [],
    verb: null,
    source: SRC,
  },

  // ── numbers (numerals) ──
  eins: {
    id: 'eins',
    de: 'eins',
    en: ['one'],
    pos: 'num',
    article: null,
    ipa: '[aɪ̯ns]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['numbers'],
    examples: [],
    verb: null,
    source: SRC,
  },
  zwei: {
    id: 'zwei',
    de: 'zwei',
    en: ['two'],
    pos: 'num',
    article: null,
    ipa: '[t͡svaɪ̯]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['numbers'],
    examples: [],
    verb: null,
    source: SRC,
  },
  drei: {
    id: 'drei',
    de: 'drei',
    en: ['three'],
    pos: 'num',
    article: null,
    ipa: '[dʁaɪ̯]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['numbers'],
    examples: [],
    verb: null,
    source: SRC,
  },
  vier: {
    id: 'vier',
    de: 'vier',
    en: ['four'],
    pos: 'num',
    article: null,
    ipa: '[fiːɐ̯]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['numbers'],
    examples: [],
    verb: null,
    source: SRC,
  },
  fünf: {
    id: 'fünf',
    de: 'fünf',
    en: ['five'],
    pos: 'num',
    article: null,
    ipa: '[fʏnf]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['numbers'],
    examples: [],
    verb: null,
    source: SRC,
  },
  sechs: {
    id: 'sechs',
    de: 'sechs',
    en: ['six'],
    pos: 'num',
    article: null,
    ipa: '[zɛks]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['numbers'],
    examples: [],
    verb: null,
    source: SRC,
  },
  sieben: {
    id: 'sieben',
    de: 'sieben',
    en: ['seven'],
    pos: 'num',
    article: null,
    ipa: '[ˈziːbn̩]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['numbers'],
    examples: [],
    verb: null,
    source: SRC,
  },
  acht: {
    id: 'acht',
    de: 'acht',
    en: ['eight'],
    pos: 'num',
    article: null,
    ipa: '[axt]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['numbers'],
    examples: [],
    verb: null,
    source: SRC,
  },
  neun: {
    id: 'neun',
    de: 'neun',
    en: ['nine'],
    pos: 'num',
    article: null,
    ipa: '[nɔɪ̯n]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['numbers'],
    examples: [],
    verb: null,
    source: SRC,
  },
  zehn: {
    id: 'zehn',
    de: 'zehn',
    en: ['ten'],
    pos: 'num',
    article: null,
    ipa: '[t͡seːn]',
    plural: null,
    cefr: 'A1',
    freqRank: null,
    tags: ['numbers'],
    examples: [],
    verb: null,
    source: SRC,
  },
};
